-- ====================================================================
-- SQL SCHEMA MIGRATION: ORDERS & ORDER ITEMS TABLES
-- Run these commands in the Supabase SQL Editor to support order saves.
-- ====================================================================

-- 1. Create orders table
CREATE TABLE IF NOT EXISTS public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name text NOT NULL,
  phone text NOT NULL,
  address text NOT NULL,
  pincode text NOT NULL,
  total_amount numeric NOT NULL,
  payment_method text NOT NULL DEFAULT 'WhatsApp Checkout',
  status text NOT NULL DEFAULT 'Pending',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create order_items table for relational items linking
CREATE TABLE IF NOT EXISTS public.order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id bigint,
  product_name text NOT NULL,
  price numeric NOT NULL,
  qty integer NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- 4. Enable public read/write access policies
CREATE POLICY "Allow read/write access to orders for everyone" 
  ON public.orders FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow read/write access to order_items for everyone" 
  ON public.order_items FOR ALL USING (true) WITH CHECK (true);
